# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: archlinux-latex
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Install Package Requirements
        run: sudo pacman -Syu rpm-tools meson make gcc base-devel 
      - name: Build RPM Package
        run: ./package.sh rpm
      - name: Build Arch Package
        run: ./package.sh arch
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.github_token }}"
          automatic_release_tag: "v${{ env.BRANCH_NAME }}"
          prerelease: true
          title: "Latest v${{ env.BRANCH_NAME }} Build"
          files: |
            target/rpm/RPMS/x86_64/stardock-${{ env.BRANCH_NAME }}-1.x86_64.rpm
            target/rpm/RPMS/x86_64/stardock-devel-${{ env.BRANCH_NAME }}-1.x86_64.rpm
            target/arch/stardock-${{ env.BRANCH_NAME }}-1-x86_64.pkg.tar.zst
